### ISSUE TITLE
API Design Guidelines: Fundamentals

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#1]
# 내용
API Design Guidelines의 Fundamentals 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by Kioding** [comment]
1. 작성자: Kio

2. 작성 유형 (new/edit): new

3. 마감 일자: 2022년 3월 17일

4. 작업 내용

- API Design Guidelines의 Fundamentals 파트 번역
