### ISSUE TITLE
API Design Guidelines: Naming(Promote Clear Usage)

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#2]
# 내용

API Design Guidelines의 Naming - `Promote Clear Usage` 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by soleJin** [comment]
1. 작성자: Sole

2. 작성 유형 (new/edit): new

3. 마감 일자: 2022년 3월 17일

4. 작업 내용

- API Design Guidelines의 Naming - Promote Clear Usage 파트 번역
