### ISSUE TITLE
API Design Guidelines: Naming(Strive for Fluent Usage)

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#3]
# 내용

API Design Guidelines의 Naming - `Strive for Fluent Usage` 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by iluxsm** [comment]
1. 작성자: Glenn

2. 작성 유형 (new/edit): new

3. 마감 일자: 2022.03.17

4. 작업 내용
- API Design Guidelines의 Naming - Strive for Fluent Usage 파트 번역
