### ISSUE TITLE
API Design Guidelines: Naming(Use Terminology Well)

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#4]
# 내용

API Design Guidelines의 Naming - `Use Terminology Well` 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by Babywalnut** [comment]
작성자: Bobby

작성 유형 (new/edit): new

마감 일자: 2022년 3월 17일

작업 내용

API Design Guidelines의 Naming - Use Terminology Well 파트 번역
