### ISSUE TITLE
API Design Guidelines: Conventions(General Conventions)

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#5]
# 내용

API Design Guidelines의 Conventions - `General Conventions` 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by hayeonhee** [comment]
1. 작성자: yeha
2. 작성 유형 (new/edit): new
3. 마감 일자: 2022.3.17
4. 작업 내용
- API Design Guidelines의 Conventions - General Conventions 파트 번역
