### ISSUE TITLE
API Design Guidelines: Conventions(Parameters)

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#6]
# 내용

API Design Guidelines의 Conventions - `Parameter` 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by ye-ha** [comment]
1. 작성자: yeha
2. 작성 유형 (new/edit): new
3. 마감 일자: 2022.3.17
4. 작업 내용 
- API Design Guidelines의 Conventions - Parameters 파트 번역

**Comment by GREENOVER** [comment]
1. 작성자: green
2. 작성 유형 (new/edit): new
3. 마감 일자: 2022.3.17
4. 작업 내용
- API Design Guidelines의 Conventions - Parameters 파트 번역
