### ISSUE TITLE
API Design Guidelines: Special Instructions

### ISSUE THREAD

**Issue by odong-Tree** [yagom-academy/swift-doc-kor#8]
# 내용

API Design Guidelines의 Special Intstructions 파트 번역

<br>

### 4. 작업 내용
- 
-

**Comment by soo941226** [comment]
작성자: soo941226

작성 유형 (new/edit): new

마감 일자: 2022년 3월 17일

작업 내용: API Design Guidelines의 Special Intstructions 파트 번역
